#!/usr/bin/env node

const { spawnSync } = require('node:child_process');

const result = spawnSync('npm', ['run', 'precommit'], {
  stdio: 'inherit',
  shell: process.platform === 'win32',
});

if (result.error) {
  console.error(result.error);
  process.exit(1);
}

process.exit(result.status || 0);
