[package]
name = "js_vm_runtime_core"
version.workspace = true
edition.workspace = true

[dependencies]
js_token_core.workspace = true
wasm-bindgen.workspace = true
js-sys.workspace = true

[features]
default = [
    "bigint",
    "generator",
    "host-builtins",
    "module",
    "proxy",
    "regexp",
    "test262-compat",
]
array-builtins = []
bigint = []
compact-errors = []
debugger = []
function-builtins = []
generator = []
host-builtins = [
    "array-builtins",
    "function-builtins",
    "object-builtins",
    "string-builtins",
]
module = []
object-builtins = []
proxy = []
regexp = []
runtime-profile = []
source-map = []
string-builtins = []
test262-compat = ["test262-eval"]
test262-eval = []

[lib]
crate-type = ["rlib"]
